// This file is @generated by prost-build.
/// 注册请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterRequest {
    /// 用户名
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    /// 邮箱
    #[prost(string, tag = "2")]
    pub email: ::prost::alloc::string::String,
    /// 密码
    #[prost(string, tag = "3")]
    pub password: ::prost::alloc::string::String,
    /// 显示名称
    #[prost(string, tag = "4")]
    pub display_name: ::prost::alloc::string::String,
    /// 电话
    #[prost(string, tag = "5")]
    pub phone: ::prost::alloc::string::String,
    /// 租户 ID
    #[prost(string, tag = "6")]
    pub tenant_id: ::prost::alloc::string::String,
    /// 角色 ID 列表
    #[prost(string, repeated, tag = "7")]
    pub role_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// 注册响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterResponse {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 用户信息
    #[prost(message, optional, tag = "2")]
    pub user: ::core::option::Option<User>,
}
/// 获取用户请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
/// 获取用户响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserResponse {
    /// 用户信息
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<User>,
}
/// 获取当前用户请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCurrentUserRequest {
    /// 访问令牌
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
}
/// 获取当前用户响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCurrentUserResponse {
    /// 用户信息
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<User>,
}
/// 更新用户请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateUserRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 用户名
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    /// 邮箱
    #[prost(string, tag = "3")]
    pub email: ::prost::alloc::string::String,
    /// 显示名称
    #[prost(string, tag = "4")]
    pub display_name: ::prost::alloc::string::String,
    /// 电话
    #[prost(string, tag = "5")]
    pub phone: ::prost::alloc::string::String,
    /// 头像 URL
    #[prost(string, tag = "6")]
    pub avatar_url: ::prost::alloc::string::String,
    /// 语言
    #[prost(string, tag = "7")]
    pub language: ::prost::alloc::string::String,
    /// 时区
    #[prost(string, tag = "8")]
    pub timezone: ::prost::alloc::string::String,
    /// 状态
    #[prost(string, tag = "9")]
    pub status: ::prost::alloc::string::String,
}
/// 更新用户响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateUserResponse {
    /// 更新后的用户信息
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<User>,
}
/// 更新个人资料请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateProfileRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 显示名称
    #[prost(string, tag = "2")]
    pub display_name: ::prost::alloc::string::String,
    /// 邮箱
    #[prost(string, tag = "3")]
    pub email: ::prost::alloc::string::String,
    /// 电话
    #[prost(string, tag = "4")]
    pub phone: ::prost::alloc::string::String,
    /// 头像 URL
    #[prost(string, tag = "5")]
    pub avatar_url: ::prost::alloc::string::String,
    /// 语言
    #[prost(string, tag = "6")]
    pub language: ::prost::alloc::string::String,
    /// 时区
    #[prost(string, tag = "7")]
    pub timezone: ::prost::alloc::string::String,
}
/// 更新个人资料响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateProfileResponse {
    /// 更新后的用户信息
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<User>,
}
/// 删除用户请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteUserRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
/// 用户列表请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListUsersRequest {
    /// 租户 ID 过滤
    #[prost(string, tag = "1")]
    pub tenant_id: ::prost::alloc::string::String,
    /// 状态过滤
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
    /// 搜索关键词（用户名、邮箱、显示名称）
    #[prost(string, tag = "3")]
    pub search: ::prost::alloc::string::String,
    /// 角色 ID 过滤
    #[prost(string, repeated, tag = "4")]
    pub role_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 页码
    #[prost(int32, tag = "100")]
    pub page: i32,
    /// 每页大小
    #[prost(int32, tag = "101")]
    pub page_size: i32,
}
/// 用户列表响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListUsersResponse {
    /// 用户列表
    #[prost(message, repeated, tag = "1")]
    pub users: ::prost::alloc::vec::Vec<User>,
    /// 当前页码
    #[prost(int32, tag = "2")]
    pub page: i32,
    /// 每页大小
    #[prost(int32, tag = "3")]
    pub page_size: i32,
    /// 总记录数
    #[prost(int64, tag = "4")]
    pub total: i64,
    /// 总页数
    #[prost(int32, tag = "5")]
    pub total_pages: i32,
}
/// 激活用户请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActivateUserRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
/// 激活用户响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActivateUserResponse {
    /// 用户信息
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<User>,
}
/// 停用用户请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeactivateUserRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 停用原因
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
/// 停用用户响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeactivateUserResponse {
    /// 用户信息
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<User>,
}
/// 锁定用户请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LockUserRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 锁定原因
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
/// 锁定用户响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LockUserResponse {
    /// 用户信息
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<User>,
}
/// 解锁用户请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnlockUserRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
/// 解锁用户响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnlockUserResponse {
    /// 用户信息
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<User>,
}
/// 分配角色请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AssignRolesRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 角色 ID 列表
    #[prost(string, repeated, tag = "2")]
    pub role_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// 分配角色响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AssignRolesResponse {
    /// 用户信息
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<User>,
}
/// 移除角色请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveRolesRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 角色 ID 列表
    #[prost(string, repeated, tag = "2")]
    pub role_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// 移除角色响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveRolesResponse {
    /// 用户信息
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<User>,
}
/// 获取用户角色请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserRolesRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
/// 获取用户角色响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserRolesResponse {
    /// 角色列表
    #[prost(message, repeated, tag = "1")]
    pub roles: ::prost::alloc::vec::Vec<Role>,
}
/// 用户
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct User {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 用户名
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    /// 邮箱
    #[prost(string, tag = "3")]
    pub email: ::prost::alloc::string::String,
    /// 显示名称
    #[prost(string, tag = "4")]
    pub display_name: ::prost::alloc::string::String,
    /// 电话
    #[prost(string, tag = "5")]
    pub phone: ::prost::alloc::string::String,
    /// 头像 URL
    #[prost(string, tag = "6")]
    pub avatar_url: ::prost::alloc::string::String,
    /// 租户 ID
    #[prost(string, tag = "7")]
    pub tenant_id: ::prost::alloc::string::String,
    /// 角色 ID 列表
    #[prost(string, repeated, tag = "8")]
    pub role_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 状态 (ACTIVE, INACTIVE, LOCKED)
    #[prost(string, tag = "9")]
    pub status: ::prost::alloc::string::String,
    /// 语言
    #[prost(string, tag = "10")]
    pub language: ::prost::alloc::string::String,
    /// 时区
    #[prost(string, tag = "11")]
    pub timezone: ::prost::alloc::string::String,
    /// 是否启用双因子认证
    #[prost(bool, tag = "12")]
    pub two_factor_enabled: bool,
    /// 最后登录时间
    #[prost(message, optional, tag = "13")]
    pub last_login_at: ::core::option::Option<::prost_types::Timestamp>,
    /// 审计信息
    #[prost(message, optional, tag = "90")]
    pub audit_info: ::core::option::Option<AuditInfo>,
}
/// 审计信息
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuditInfo {
    /// 创建时间
    #[prost(message, optional, tag = "1")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    /// 创建人
    #[prost(string, tag = "2")]
    pub created_by: ::prost::alloc::string::String,
    /// 更新时间
    #[prost(message, optional, tag = "3")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
    /// 更新人
    #[prost(string, tag = "4")]
    pub updated_by: ::prost::alloc::string::String,
}
/// 角色（简化版，完整定义在 rbac.proto）
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Role {
    /// 角色 ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 角色代码
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
    /// 角色名称
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    /// 角色描述
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
}
/// Generated server implementations.
pub mod user_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with UserServiceServer.
    #[async_trait]
    pub trait UserService: std::marker::Send + std::marker::Sync + 'static {
        /// 注册新用户
        async fn register(
            &self,
            request: tonic::Request<super::RegisterRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterResponse>,
            tonic::Status,
        >;
        /// 获取用户信息
        async fn get_user(
            &self,
            request: tonic::Request<super::GetUserRequest>,
        ) -> std::result::Result<tonic::Response<super::GetUserResponse>, tonic::Status>;
        /// 获取当前用户（从 AuthService 迁移）
        async fn get_current_user(
            &self,
            request: tonic::Request<super::GetCurrentUserRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetCurrentUserResponse>,
            tonic::Status,
        >;
        /// 更新用户信息
        async fn update_user(
            &self,
            request: tonic::Request<super::UpdateUserRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateUserResponse>,
            tonic::Status,
        >;
        /// 更新个人资料（从 AuthService 迁移）
        async fn update_profile(
            &self,
            request: tonic::Request<super::UpdateProfileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateProfileResponse>,
            tonic::Status,
        >;
        /// 删除用户
        async fn delete_user(
            &self,
            request: tonic::Request<super::DeleteUserRequest>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status>;
        /// 用户列表查询
        async fn list_users(
            &self,
            request: tonic::Request<super::ListUsersRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListUsersResponse>,
            tonic::Status,
        >;
        /// 激活用户
        async fn activate_user(
            &self,
            request: tonic::Request<super::ActivateUserRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ActivateUserResponse>,
            tonic::Status,
        >;
        /// 停用用户
        async fn deactivate_user(
            &self,
            request: tonic::Request<super::DeactivateUserRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeactivateUserResponse>,
            tonic::Status,
        >;
        /// 锁定用户
        async fn lock_user(
            &self,
            request: tonic::Request<super::LockUserRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LockUserResponse>,
            tonic::Status,
        >;
        /// 解锁用户
        async fn unlock_user(
            &self,
            request: tonic::Request<super::UnlockUserRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UnlockUserResponse>,
            tonic::Status,
        >;
        /// 分配角色
        async fn assign_roles(
            &self,
            request: tonic::Request<super::AssignRolesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AssignRolesResponse>,
            tonic::Status,
        >;
        /// 移除角色
        async fn remove_roles(
            &self,
            request: tonic::Request<super::RemoveRolesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RemoveRolesResponse>,
            tonic::Status,
        >;
        /// 获取用户角色
        async fn get_user_roles(
            &self,
            request: tonic::Request<super::GetUserRolesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetUserRolesResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct UserServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> UserServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for UserServiceServer<T>
    where
        T: UserService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/cuba.iam.user.UserService/Register" => {
                    #[allow(non_camel_case_types)]
                    struct RegisterSvc<T: UserService>(pub Arc<T>);
                    impl<
                        T: UserService,
                    > tonic::server::UnaryService<super::RegisterRequest>
                    for RegisterSvc<T> {
                        type Response = super::RegisterResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RegisterRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UserService>::register(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RegisterSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.user.UserService/GetUser" => {
                    #[allow(non_camel_case_types)]
                    struct GetUserSvc<T: UserService>(pub Arc<T>);
                    impl<
                        T: UserService,
                    > tonic::server::UnaryService<super::GetUserRequest>
                    for GetUserSvc<T> {
                        type Response = super::GetUserResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetUserRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UserService>::get_user(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetUserSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.user.UserService/GetCurrentUser" => {
                    #[allow(non_camel_case_types)]
                    struct GetCurrentUserSvc<T: UserService>(pub Arc<T>);
                    impl<
                        T: UserService,
                    > tonic::server::UnaryService<super::GetCurrentUserRequest>
                    for GetCurrentUserSvc<T> {
                        type Response = super::GetCurrentUserResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetCurrentUserRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UserService>::get_current_user(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetCurrentUserSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.user.UserService/UpdateUser" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateUserSvc<T: UserService>(pub Arc<T>);
                    impl<
                        T: UserService,
                    > tonic::server::UnaryService<super::UpdateUserRequest>
                    for UpdateUserSvc<T> {
                        type Response = super::UpdateUserResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdateUserRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UserService>::update_user(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateUserSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.user.UserService/UpdateProfile" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateProfileSvc<T: UserService>(pub Arc<T>);
                    impl<
                        T: UserService,
                    > tonic::server::UnaryService<super::UpdateProfileRequest>
                    for UpdateProfileSvc<T> {
                        type Response = super::UpdateProfileResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdateProfileRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UserService>::update_profile(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateProfileSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.user.UserService/DeleteUser" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteUserSvc<T: UserService>(pub Arc<T>);
                    impl<
                        T: UserService,
                    > tonic::server::UnaryService<super::DeleteUserRequest>
                    for DeleteUserSvc<T> {
                        type Response = ();
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeleteUserRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UserService>::delete_user(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteUserSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.user.UserService/ListUsers" => {
                    #[allow(non_camel_case_types)]
                    struct ListUsersSvc<T: UserService>(pub Arc<T>);
                    impl<
                        T: UserService,
                    > tonic::server::UnaryService<super::ListUsersRequest>
                    for ListUsersSvc<T> {
                        type Response = super::ListUsersResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListUsersRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UserService>::list_users(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListUsersSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.user.UserService/ActivateUser" => {
                    #[allow(non_camel_case_types)]
                    struct ActivateUserSvc<T: UserService>(pub Arc<T>);
                    impl<
                        T: UserService,
                    > tonic::server::UnaryService<super::ActivateUserRequest>
                    for ActivateUserSvc<T> {
                        type Response = super::ActivateUserResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ActivateUserRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UserService>::activate_user(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ActivateUserSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.user.UserService/DeactivateUser" => {
                    #[allow(non_camel_case_types)]
                    struct DeactivateUserSvc<T: UserService>(pub Arc<T>);
                    impl<
                        T: UserService,
                    > tonic::server::UnaryService<super::DeactivateUserRequest>
                    for DeactivateUserSvc<T> {
                        type Response = super::DeactivateUserResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeactivateUserRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UserService>::deactivate_user(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeactivateUserSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.user.UserService/LockUser" => {
                    #[allow(non_camel_case_types)]
                    struct LockUserSvc<T: UserService>(pub Arc<T>);
                    impl<
                        T: UserService,
                    > tonic::server::UnaryService<super::LockUserRequest>
                    for LockUserSvc<T> {
                        type Response = super::LockUserResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LockUserRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UserService>::lock_user(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LockUserSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.user.UserService/UnlockUser" => {
                    #[allow(non_camel_case_types)]
                    struct UnlockUserSvc<T: UserService>(pub Arc<T>);
                    impl<
                        T: UserService,
                    > tonic::server::UnaryService<super::UnlockUserRequest>
                    for UnlockUserSvc<T> {
                        type Response = super::UnlockUserResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UnlockUserRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UserService>::unlock_user(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UnlockUserSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.user.UserService/AssignRoles" => {
                    #[allow(non_camel_case_types)]
                    struct AssignRolesSvc<T: UserService>(pub Arc<T>);
                    impl<
                        T: UserService,
                    > tonic::server::UnaryService<super::AssignRolesRequest>
                    for AssignRolesSvc<T> {
                        type Response = super::AssignRolesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AssignRolesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UserService>::assign_roles(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AssignRolesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.user.UserService/RemoveRoles" => {
                    #[allow(non_camel_case_types)]
                    struct RemoveRolesSvc<T: UserService>(pub Arc<T>);
                    impl<
                        T: UserService,
                    > tonic::server::UnaryService<super::RemoveRolesRequest>
                    for RemoveRolesSvc<T> {
                        type Response = super::RemoveRolesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RemoveRolesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UserService>::remove_roles(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RemoveRolesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.user.UserService/GetUserRoles" => {
                    #[allow(non_camel_case_types)]
                    struct GetUserRolesSvc<T: UserService>(pub Arc<T>);
                    impl<
                        T: UserService,
                    > tonic::server::UnaryService<super::GetUserRolesRequest>
                    for GetUserRolesSvc<T> {
                        type Response = super::GetUserRolesResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetUserRolesRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as UserService>::get_user_roles(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetUserRolesSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for UserServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "cuba.iam.user.UserService";
    impl<T> tonic::server::NamedService for UserServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
