// This file is @generated by prost-build.
/// 注册请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterRequest {
    /// 用户名
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    /// 邮箱
    #[prost(string, tag = "2")]
    pub email: ::prost::alloc::string::String,
    /// 密码
    #[prost(string, tag = "3")]
    pub password: ::prost::alloc::string::String,
    /// 显示名称
    #[prost(string, tag = "4")]
    pub display_name: ::prost::alloc::string::String,
    /// 电话
    #[prost(string, tag = "5")]
    pub phone: ::prost::alloc::string::String,
    /// 租户 ID
    #[prost(string, tag = "6")]
    pub tenant_id: ::prost::alloc::string::String,
    /// 角色 ID 列表
    #[prost(string, repeated, tag = "7")]
    pub role_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// 注册响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RegisterResponse {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 用户信息
    #[prost(message, optional, tag = "2")]
    pub user: ::core::option::Option<User>,
}
/// 获取用户请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
/// 获取用户响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserResponse {
    /// 用户信息
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<User>,
}
/// 获取当前用户请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCurrentUserRequest {
    /// 访问令牌
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
}
/// 获取当前用户响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetCurrentUserResponse {
    /// 用户信息
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<User>,
}
/// 更新用户请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateUserRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 用户名
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    /// 邮箱
    #[prost(string, tag = "3")]
    pub email: ::prost::alloc::string::String,
    /// 显示名称
    #[prost(string, tag = "4")]
    pub display_name: ::prost::alloc::string::String,
    /// 电话
    #[prost(string, tag = "5")]
    pub phone: ::prost::alloc::string::String,
    /// 头像 URL
    #[prost(string, tag = "6")]
    pub avatar_url: ::prost::alloc::string::String,
    /// 语言
    #[prost(string, tag = "7")]
    pub language: ::prost::alloc::string::String,
    /// 时区
    #[prost(string, tag = "8")]
    pub timezone: ::prost::alloc::string::String,
    /// 状态
    #[prost(string, tag = "9")]
    pub status: ::prost::alloc::string::String,
}
/// 更新用户响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateUserResponse {
    /// 更新后的用户信息
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<User>,
}
/// 更新个人资料请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateProfileRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 显示名称
    #[prost(string, tag = "2")]
    pub display_name: ::prost::alloc::string::String,
    /// 邮箱
    #[prost(string, tag = "3")]
    pub email: ::prost::alloc::string::String,
    /// 电话
    #[prost(string, tag = "4")]
    pub phone: ::prost::alloc::string::String,
    /// 头像 URL
    #[prost(string, tag = "5")]
    pub avatar_url: ::prost::alloc::string::String,
    /// 语言
    #[prost(string, tag = "6")]
    pub language: ::prost::alloc::string::String,
    /// 时区
    #[prost(string, tag = "7")]
    pub timezone: ::prost::alloc::string::String,
}
/// 更新个人资料响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateProfileResponse {
    /// 更新后的用户信息
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<User>,
}
/// 删除用户请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteUserRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
/// 用户列表请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListUsersRequest {
    /// 租户 ID 过滤
    #[prost(string, tag = "1")]
    pub tenant_id: ::prost::alloc::string::String,
    /// 状态过滤
    #[prost(string, tag = "2")]
    pub status: ::prost::alloc::string::String,
    /// 搜索关键词（用户名、邮箱、显示名称）
    #[prost(string, tag = "3")]
    pub search: ::prost::alloc::string::String,
    /// 角色 ID 过滤
    #[prost(string, repeated, tag = "4")]
    pub role_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 页码
    #[prost(int32, tag = "100")]
    pub page: i32,
    /// 每页大小
    #[prost(int32, tag = "101")]
    pub page_size: i32,
}
/// 用户列表响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListUsersResponse {
    /// 用户列表
    #[prost(message, repeated, tag = "1")]
    pub users: ::prost::alloc::vec::Vec<User>,
    /// 当前页码
    #[prost(int32, tag = "2")]
    pub page: i32,
    /// 每页大小
    #[prost(int32, tag = "3")]
    pub page_size: i32,
    /// 总记录数
    #[prost(int64, tag = "4")]
    pub total: i64,
    /// 总页数
    #[prost(int32, tag = "5")]
    pub total_pages: i32,
}
/// 激活用户请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActivateUserRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
/// 激活用户响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ActivateUserResponse {
    /// 用户信息
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<User>,
}
/// 停用用户请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeactivateUserRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 停用原因
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
/// 停用用户响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeactivateUserResponse {
    /// 用户信息
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<User>,
}
/// 锁定用户请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LockUserRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 锁定原因
    #[prost(string, tag = "2")]
    pub reason: ::prost::alloc::string::String,
}
/// 锁定用户响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LockUserResponse {
    /// 用户信息
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<User>,
}
/// 解锁用户请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnlockUserRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
/// 解锁用户响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UnlockUserResponse {
    /// 用户信息
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<User>,
}
/// 分配角色请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AssignRolesRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 角色 ID 列表
    #[prost(string, repeated, tag = "2")]
    pub role_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// 分配角色响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AssignRolesResponse {
    /// 用户信息
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<User>,
}
/// 移除角色请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveRolesRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 角色 ID 列表
    #[prost(string, repeated, tag = "2")]
    pub role_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// 移除角色响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RemoveRolesResponse {
    /// 用户信息
    #[prost(message, optional, tag = "1")]
    pub user: ::core::option::Option<User>,
}
/// 获取用户角色请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserRolesRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
/// 获取用户角色响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserRolesResponse {
    /// 角色列表
    #[prost(message, repeated, tag = "1")]
    pub roles: ::prost::alloc::vec::Vec<Role>,
}
/// 发送邮箱验证码请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendEmailVerificationRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
/// 发送邮箱验证码响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendEmailVerificationResponse {
    /// 是否成功
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// 消息
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// 验证码有效期（秒）
    #[prost(int32, tag = "3")]
    pub expires_in_seconds: i32,
}
/// 验证邮箱请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VerifyEmailRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 验证码
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
}
/// 验证邮箱响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VerifyEmailResponse {
    /// 是否成功
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// 消息
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// 发送手机验证码请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendPhoneVerificationRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
/// 发送手机验证码响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SendPhoneVerificationResponse {
    /// 是否成功
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// 消息
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
    /// 验证码有效期（秒）
    #[prost(int32, tag = "3")]
    pub expires_in_seconds: i32,
}
/// 验证手机请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VerifyPhoneRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 验证码
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
}
/// 验证手机响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct VerifyPhoneResponse {
    /// 是否成功
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// 消息
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// 用户
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct User {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 用户名
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    /// 邮箱
    #[prost(string, tag = "3")]
    pub email: ::prost::alloc::string::String,
    /// 显示名称
    #[prost(string, tag = "4")]
    pub display_name: ::prost::alloc::string::String,
    /// 电话
    #[prost(string, tag = "5")]
    pub phone: ::prost::alloc::string::String,
    /// 头像 URL
    #[prost(string, tag = "6")]
    pub avatar_url: ::prost::alloc::string::String,
    /// 租户 ID
    #[prost(string, tag = "7")]
    pub tenant_id: ::prost::alloc::string::String,
    /// 角色 ID 列表
    #[prost(string, repeated, tag = "8")]
    pub role_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 状态 (ACTIVE, INACTIVE, LOCKED)
    #[prost(string, tag = "9")]
    pub status: ::prost::alloc::string::String,
    /// 语言
    #[prost(string, tag = "10")]
    pub language: ::prost::alloc::string::String,
    /// 时区
    #[prost(string, tag = "11")]
    pub timezone: ::prost::alloc::string::String,
    /// 是否启用双因子认证
    #[prost(bool, tag = "12")]
    pub two_factor_enabled: bool,
    /// 最后登录时间
    #[prost(message, optional, tag = "13")]
    pub last_login_at: ::core::option::Option<::prost_types::Timestamp>,
    /// 审计信息
    #[prost(message, optional, tag = "90")]
    pub audit_info: ::core::option::Option<AuditInfo>,
}
/// 审计信息
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuditInfo {
    /// 创建时间
    #[prost(message, optional, tag = "1")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    /// 创建人
    #[prost(string, tag = "2")]
    pub created_by: ::prost::alloc::string::String,
    /// 更新时间
    #[prost(message, optional, tag = "3")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
    /// 更新人
    #[prost(string, tag = "4")]
    pub updated_by: ::prost::alloc::string::String,
}
/// 角色（简化版，完整定义在 rbac.proto）
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Role {
    /// 角色 ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 角色代码
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
    /// 角色名称
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    /// 角色描述
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod user_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct UserServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl UserServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> UserServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> UserServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            UserServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// 注册新用户
        pub async fn register(
            &mut self,
            request: impl tonic::IntoRequest<super::RegisterRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RegisterResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.user.UserService/Register",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.user.UserService", "Register"));
            self.inner.unary(req, path, codec).await
        }
        /// 获取用户信息
        pub async fn get_user(
            &mut self,
            request: impl tonic::IntoRequest<super::GetUserRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetUserResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.user.UserService/GetUser",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.user.UserService", "GetUser"));
            self.inner.unary(req, path, codec).await
        }
        /// 获取当前用户（从 AuthService 迁移）
        pub async fn get_current_user(
            &mut self,
            request: impl tonic::IntoRequest<super::GetCurrentUserRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetCurrentUserResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.user.UserService/GetCurrentUser",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.user.UserService", "GetCurrentUser"));
            self.inner.unary(req, path, codec).await
        }
        /// 更新用户信息
        pub async fn update_user(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateUserRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateUserResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.user.UserService/UpdateUser",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.user.UserService", "UpdateUser"));
            self.inner.unary(req, path, codec).await
        }
        /// 更新个人资料（从 AuthService 迁移）
        pub async fn update_profile(
            &mut self,
            request: impl tonic::IntoRequest<super::UpdateProfileRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateProfileResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.user.UserService/UpdateProfile",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.user.UserService", "UpdateProfile"));
            self.inner.unary(req, path, codec).await
        }
        /// 删除用户
        pub async fn delete_user(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteUserRequest>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.user.UserService/DeleteUser",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.user.UserService", "DeleteUser"));
            self.inner.unary(req, path, codec).await
        }
        /// 用户列表查询
        pub async fn list_users(
            &mut self,
            request: impl tonic::IntoRequest<super::ListUsersRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListUsersResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.user.UserService/ListUsers",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.user.UserService", "ListUsers"));
            self.inner.unary(req, path, codec).await
        }
        /// 激活用户
        pub async fn activate_user(
            &mut self,
            request: impl tonic::IntoRequest<super::ActivateUserRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ActivateUserResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.user.UserService/ActivateUser",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.user.UserService", "ActivateUser"));
            self.inner.unary(req, path, codec).await
        }
        /// 停用用户
        pub async fn deactivate_user(
            &mut self,
            request: impl tonic::IntoRequest<super::DeactivateUserRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeactivateUserResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.user.UserService/DeactivateUser",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.user.UserService", "DeactivateUser"));
            self.inner.unary(req, path, codec).await
        }
        /// 锁定用户
        pub async fn lock_user(
            &mut self,
            request: impl tonic::IntoRequest<super::LockUserRequest>,
        ) -> std::result::Result<
            tonic::Response<super::LockUserResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.user.UserService/LockUser",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.user.UserService", "LockUser"));
            self.inner.unary(req, path, codec).await
        }
        /// 解锁用户
        pub async fn unlock_user(
            &mut self,
            request: impl tonic::IntoRequest<super::UnlockUserRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UnlockUserResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.user.UserService/UnlockUser",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.user.UserService", "UnlockUser"));
            self.inner.unary(req, path, codec).await
        }
        /// 分配角色
        pub async fn assign_roles(
            &mut self,
            request: impl tonic::IntoRequest<super::AssignRolesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AssignRolesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.user.UserService/AssignRoles",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.user.UserService", "AssignRoles"));
            self.inner.unary(req, path, codec).await
        }
        /// 移除角色
        pub async fn remove_roles(
            &mut self,
            request: impl tonic::IntoRequest<super::RemoveRolesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RemoveRolesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.user.UserService/RemoveRoles",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.user.UserService", "RemoveRoles"));
            self.inner.unary(req, path, codec).await
        }
        /// 获取用户角色
        pub async fn get_user_roles(
            &mut self,
            request: impl tonic::IntoRequest<super::GetUserRolesRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetUserRolesResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.user.UserService/GetUserRoles",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.user.UserService", "GetUserRoles"));
            self.inner.unary(req, path, codec).await
        }
        /// 发送邮箱验证码
        pub async fn send_email_verification(
            &mut self,
            request: impl tonic::IntoRequest<super::SendEmailVerificationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SendEmailVerificationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.user.UserService/SendEmailVerification",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("cuba.iam.user.UserService", "SendEmailVerification"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 验证邮箱
        pub async fn verify_email(
            &mut self,
            request: impl tonic::IntoRequest<super::VerifyEmailRequest>,
        ) -> std::result::Result<
            tonic::Response<super::VerifyEmailResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.user.UserService/VerifyEmail",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.user.UserService", "VerifyEmail"));
            self.inner.unary(req, path, codec).await
        }
        /// 发送手机验证码
        pub async fn send_phone_verification(
            &mut self,
            request: impl tonic::IntoRequest<super::SendPhoneVerificationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::SendPhoneVerificationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.user.UserService/SendPhoneVerification",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("cuba.iam.user.UserService", "SendPhoneVerification"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 验证手机
        pub async fn verify_phone(
            &mut self,
            request: impl tonic::IntoRequest<super::VerifyPhoneRequest>,
        ) -> std::result::Result<
            tonic::Response<super::VerifyPhoneResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.user.UserService/VerifyPhone",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.user.UserService", "VerifyPhone"));
            self.inner.unary(req, path, codec).await
        }
    }
}
