// This file is @generated by prost-build.
/// 登录请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginRequest {
    /// 用户名或邮箱
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    /// 密码
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    /// 租户 ID
    #[prost(string, tag = "3")]
    pub tenant_id: ::prost::alloc::string::String,
    /// 设备信息
    #[prost(string, tag = "4")]
    pub device_info: ::prost::alloc::string::String,
    /// IP 地址
    #[prost(string, tag = "5")]
    pub ip_address: ::prost::alloc::string::String,
}
/// 登录响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginResponse {
    /// 访问令牌
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// 刷新令牌
    #[prost(string, tag = "2")]
    pub refresh_token: ::prost::alloc::string::String,
    /// 过期时间（秒）
    #[prost(int64, tag = "3")]
    pub expires_in: i64,
    /// 令牌类型
    #[prost(string, tag = "4")]
    pub token_type: ::prost::alloc::string::String,
    /// 用户信息
    #[prost(message, optional, tag = "5")]
    pub user: ::core::option::Option<User>,
    /// 是否需要 2FA
    #[prost(bool, tag = "6")]
    pub require_2fa: bool,
    /// 会话 ID（用于 2FA）
    #[prost(string, tag = "7")]
    pub session_id: ::prost::alloc::string::String,
}
/// 登出请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogoutRequest {
    /// 访问令牌
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// 是否登出所有设备
    #[prost(bool, tag = "2")]
    pub logout_all_devices: bool,
}
/// 登出响应
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LogoutResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
/// 刷新令牌请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RefreshTokenRequest {
    #[prost(string, tag = "1")]
    pub refresh_token: ::prost::alloc::string::String,
}
/// 刷新令牌响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RefreshTokenResponse {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub refresh_token: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub expires_in: i64,
}
/// 验证令牌请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidateTokenRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
}
/// 验证令牌响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidateTokenResponse {
    #[prost(bool, tag = "1")]
    pub valid: bool,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub permissions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "5")]
    pub expires_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// 修改密码请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChangePasswordRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub old_password: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub new_password: ::prost::alloc::string::String,
}
/// 修改密码响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChangePasswordResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// 请求重置密码请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestPasswordResetRequest {
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub tenant_id: ::prost::alloc::string::String,
}
/// 请求重置密码响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestPasswordResetResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// 重置密码请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResetPasswordRequest {
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reset_token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub new_password: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub tenant_id: ::prost::alloc::string::String,
}
/// 重置密码响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResetPasswordResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// 启用 2FA 请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Enable2FaRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// TOTP, SMS, EMAIL
    #[prost(string, tag = "2")]
    pub method: ::prost::alloc::string::String,
    /// 验证码（可选，用于确认启用）
    #[prost(string, tag = "3")]
    pub verification_code: ::prost::alloc::string::String,
}
/// 启用 2FA 响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Enable2FaResponse {
    /// TOTP secret（Base32 编码）
    #[prost(string, tag = "1")]
    pub secret: ::prost::alloc::string::String,
    /// QR 码 URL
    #[prost(string, tag = "2")]
    pub qr_code_url: ::prost::alloc::string::String,
    /// 备份码（仅首次返回）
    #[prost(string, repeated, tag = "3")]
    pub backup_codes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 是否已启用（需要验证码确认）
    #[prost(bool, tag = "4")]
    pub enabled: bool,
}
/// 禁用 2FA 请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Disable2FaRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 密码验证
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
/// 禁用 2FA 响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Disable2FaResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// 验证 2FA 请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Verify2FaRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub tenant_id: ::prost::alloc::string::String,
}
/// 验证 2FA 响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Verify2FaResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub refresh_token: ::prost::alloc::string::String,
    /// 过期时间（秒）
    #[prost(int64, tag = "4")]
    pub expires_in: i64,
}
/// 获取活跃会话请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetActiveSessionsRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
/// 获取活跃会话响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetActiveSessionsResponse {
    #[prost(message, repeated, tag = "1")]
    pub sessions: ::prost::alloc::vec::Vec<Session>,
}
/// 撤销会话请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevokeSessionRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
}
/// 撤销会话响应
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RevokeSessionResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
/// 开始 WebAuthn 注册请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartWebAuthnRegistrationRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 凭证名称（如 "YubiKey 5"）
    #[prost(string, tag = "2")]
    pub credential_name: ::prost::alloc::string::String,
}
/// 开始 WebAuthn 注册响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartWebAuthnRegistrationResponse {
    /// 挑战（Base64 编码）
    #[prost(string, tag = "1")]
    pub challenge: ::prost::alloc::string::String,
    /// Relying Party ID
    #[prost(string, tag = "2")]
    pub rp_id: ::prost::alloc::string::String,
    /// Relying Party 名称
    #[prost(string, tag = "3")]
    pub rp_name: ::prost::alloc::string::String,
    /// 用户 ID（Base64 编码）
    #[prost(string, tag = "4")]
    pub user_id: ::prost::alloc::string::String,
    /// 用户名
    #[prost(string, tag = "5")]
    pub user_name: ::prost::alloc::string::String,
    /// 用户显示名称
    #[prost(string, tag = "6")]
    pub user_display_name: ::prost::alloc::string::String,
    /// 排除的凭证 ID（Base64 编码）
    #[prost(string, repeated, tag = "7")]
    pub exclude_credentials: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 注册状态（用于完成注册）
    #[prost(string, tag = "8")]
    pub registration_state: ::prost::alloc::string::String,
}
/// 完成 WebAuthn 注册请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FinishWebAuthnRegistrationRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 凭证名称
    #[prost(string, tag = "2")]
    pub credential_name: ::prost::alloc::string::String,
    /// 注册状态
    #[prost(string, tag = "3")]
    pub registration_state: ::prost::alloc::string::String,
    /// 凭证响应（JSON 格式）
    #[prost(string, tag = "4")]
    pub credential_response: ::prost::alloc::string::String,
}
/// 完成 WebAuthn 注册响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FinishWebAuthnRegistrationResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// 凭证 ID
    #[prost(string, tag = "2")]
    pub credential_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
/// 开始 WebAuthn 认证请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartWebAuthnAuthenticationRequest {
    /// 用户名或邮箱
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    /// 租户 ID
    #[prost(string, tag = "2")]
    pub tenant_id: ::prost::alloc::string::String,
}
/// 开始 WebAuthn 认证响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartWebAuthnAuthenticationResponse {
    /// 挑战（Base64 编码）
    #[prost(string, tag = "1")]
    pub challenge: ::prost::alloc::string::String,
    /// Relying Party ID
    #[prost(string, tag = "2")]
    pub rp_id: ::prost::alloc::string::String,
    /// 允许的凭证 ID（Base64 编码）
    #[prost(string, repeated, tag = "3")]
    pub allow_credentials: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 认证状态（用于完成认证）
    #[prost(string, tag = "4")]
    pub authentication_state: ::prost::alloc::string::String,
    /// 用户 ID（用于客户端）
    #[prost(string, tag = "5")]
    pub user_id: ::prost::alloc::string::String,
}
/// 完成 WebAuthn 认证请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FinishWebAuthnAuthenticationRequest {
    /// 认证状态
    #[prost(string, tag = "1")]
    pub authentication_state: ::prost::alloc::string::String,
    /// 凭证响应（JSON 格式）
    #[prost(string, tag = "2")]
    pub credential_response: ::prost::alloc::string::String,
    /// 设备信息
    #[prost(string, tag = "3")]
    pub device_info: ::prost::alloc::string::String,
    /// IP 地址
    #[prost(string, tag = "4")]
    pub ip_address: ::prost::alloc::string::String,
    /// 租户 ID
    #[prost(string, tag = "5")]
    pub tenant_id: ::prost::alloc::string::String,
}
/// 完成 WebAuthn 认证响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FinishWebAuthnAuthenticationResponse {
    /// 访问令牌
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// 刷新令牌
    #[prost(string, tag = "2")]
    pub refresh_token: ::prost::alloc::string::String,
    /// 过期时间（秒）
    #[prost(int64, tag = "3")]
    pub expires_in: i64,
    /// 令牌类型
    #[prost(string, tag = "4")]
    pub token_type: ::prost::alloc::string::String,
    /// 用户信息
    #[prost(message, optional, tag = "5")]
    pub user: ::core::option::Option<User>,
}
/// 列出 WebAuthn 凭证请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListWebAuthnCredentialsRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
/// 列出 WebAuthn 凭证响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListWebAuthnCredentialsResponse {
    #[prost(message, repeated, tag = "1")]
    pub credentials: ::prost::alloc::vec::Vec<WebAuthnCredential>,
}
/// 删除 WebAuthn 凭证请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteWebAuthnCredentialRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 凭证 ID
    #[prost(string, tag = "2")]
    pub credential_id: ::prost::alloc::string::String,
}
/// 删除 WebAuthn 凭证响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteWebAuthnCredentialResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// WebAuthn 凭证
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WebAuthnCredential {
    /// 凭证 ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 凭证名称
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// 传输方式（usb, nfc, ble, internal）
    #[prost(string, repeated, tag = "3")]
    pub transports: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 是否可备份
    #[prost(bool, tag = "4")]
    pub backup_eligible: bool,
    /// 是否已备份
    #[prost(bool, tag = "5")]
    pub backup_state: bool,
    /// 创建时间
    #[prost(message, optional, tag = "6")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    /// 最后使用时间
    #[prost(message, optional, tag = "7")]
    pub last_used_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// 用户
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct User {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub phone: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub avatar_url: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "8")]
    pub role_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "9")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub language: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub timezone: ::prost::alloc::string::String,
    #[prost(bool, tag = "12")]
    pub two_factor_enabled: bool,
    #[prost(message, optional, tag = "13")]
    pub last_login_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "14")]
    pub audit_info: ::core::option::Option<AuditInfo>,
}
/// 会话
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Session {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub device_info: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub ip_address: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub user_agent: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub is_current: bool,
    #[prost(message, optional, tag = "7")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "8")]
    pub expires_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "9")]
    pub last_activity_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// 审计信息
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuditInfo {
    #[prost(message, optional, tag = "1")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "2")]
    pub created_by: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "4")]
    pub updated_by: ::prost::alloc::string::String,
}
/// Generated client implementations.
pub mod auth_service_client {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    use tonic::codegen::http::Uri;
    #[derive(Debug, Clone)]
    pub struct AuthServiceClient<T> {
        inner: tonic::client::Grpc<T>,
    }
    impl AuthServiceClient<tonic::transport::Channel> {
        /// Attempt to create a new client by connecting to a given endpoint.
        pub async fn connect<D>(dst: D) -> Result<Self, tonic::transport::Error>
        where
            D: TryInto<tonic::transport::Endpoint>,
            D::Error: Into<StdError>,
        {
            let conn = tonic::transport::Endpoint::new(dst)?.connect().await?;
            Ok(Self::new(conn))
        }
    }
    impl<T> AuthServiceClient<T>
    where
        T: tonic::client::GrpcService<tonic::body::Body>,
        T::Error: Into<StdError>,
        T::ResponseBody: Body<Data = Bytes> + std::marker::Send + 'static,
        <T::ResponseBody as Body>::Error: Into<StdError> + std::marker::Send,
    {
        pub fn new(inner: T) -> Self {
            let inner = tonic::client::Grpc::new(inner);
            Self { inner }
        }
        pub fn with_origin(inner: T, origin: Uri) -> Self {
            let inner = tonic::client::Grpc::with_origin(inner, origin);
            Self { inner }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> AuthServiceClient<InterceptedService<T, F>>
        where
            F: tonic::service::Interceptor,
            T::ResponseBody: Default,
            T: tonic::codegen::Service<
                http::Request<tonic::body::Body>,
                Response = http::Response<
                    <T as tonic::client::GrpcService<tonic::body::Body>>::ResponseBody,
                >,
            >,
            <T as tonic::codegen::Service<
                http::Request<tonic::body::Body>,
            >>::Error: Into<StdError> + std::marker::Send + std::marker::Sync,
        {
            AuthServiceClient::new(InterceptedService::new(inner, interceptor))
        }
        /// Compress requests with the given encoding.
        ///
        /// This requires the server to support it otherwise it might respond with an
        /// error.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.send_compressed(encoding);
            self
        }
        /// Enable decompressing responses.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.inner = self.inner.accept_compressed(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_decoding_message_size(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.inner = self.inner.max_encoding_message_size(limit);
            self
        }
        /// 用户登录
        pub async fn login(
            &mut self,
            request: impl tonic::IntoRequest<super::LoginRequest>,
        ) -> std::result::Result<tonic::Response<super::LoginResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.auth.AuthService/Login",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.auth.AuthService", "Login"));
            self.inner.unary(req, path, codec).await
        }
        /// 用户登出
        pub async fn logout(
            &mut self,
            request: impl tonic::IntoRequest<super::LogoutRequest>,
        ) -> std::result::Result<tonic::Response<super::LogoutResponse>, tonic::Status> {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.auth.AuthService/Logout",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.auth.AuthService", "Logout"));
            self.inner.unary(req, path, codec).await
        }
        /// 刷新令牌
        pub async fn refresh_token(
            &mut self,
            request: impl tonic::IntoRequest<super::RefreshTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RefreshTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.auth.AuthService/RefreshToken",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.auth.AuthService", "RefreshToken"));
            self.inner.unary(req, path, codec).await
        }
        /// 验证令牌
        pub async fn validate_token(
            &mut self,
            request: impl tonic::IntoRequest<super::ValidateTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ValidateTokenResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.auth.AuthService/ValidateToken",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.auth.AuthService", "ValidateToken"));
            self.inner.unary(req, path, codec).await
        }
        /// 修改密码
        pub async fn change_password(
            &mut self,
            request: impl tonic::IntoRequest<super::ChangePasswordRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ChangePasswordResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.auth.AuthService/ChangePassword",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.auth.AuthService", "ChangePassword"));
            self.inner.unary(req, path, codec).await
        }
        /// 请求重置密码
        pub async fn request_password_reset(
            &mut self,
            request: impl tonic::IntoRequest<super::RequestPasswordResetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RequestPasswordResetResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.auth.AuthService/RequestPasswordReset",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("cuba.iam.auth.AuthService", "RequestPasswordReset"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 重置密码
        pub async fn reset_password(
            &mut self,
            request: impl tonic::IntoRequest<super::ResetPasswordRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ResetPasswordResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.auth.AuthService/ResetPassword",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.auth.AuthService", "ResetPassword"));
            self.inner.unary(req, path, codec).await
        }
        /// 启用 2FA
        pub async fn enable2_fa(
            &mut self,
            request: impl tonic::IntoRequest<super::Enable2FaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::Enable2FaResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.auth.AuthService/Enable2FA",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.auth.AuthService", "Enable2FA"));
            self.inner.unary(req, path, codec).await
        }
        /// 禁用 2FA
        pub async fn disable2_fa(
            &mut self,
            request: impl tonic::IntoRequest<super::Disable2FaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::Disable2FaResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.auth.AuthService/Disable2FA",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.auth.AuthService", "Disable2FA"));
            self.inner.unary(req, path, codec).await
        }
        /// 验证 2FA
        pub async fn verify2_fa(
            &mut self,
            request: impl tonic::IntoRequest<super::Verify2FaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::Verify2FaResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.auth.AuthService/Verify2FA",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.auth.AuthService", "Verify2FA"));
            self.inner.unary(req, path, codec).await
        }
        /// 获取活跃会话
        pub async fn get_active_sessions(
            &mut self,
            request: impl tonic::IntoRequest<super::GetActiveSessionsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetActiveSessionsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.auth.AuthService/GetActiveSessions",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new("cuba.iam.auth.AuthService", "GetActiveSessions"),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 撤销会话
        pub async fn revoke_session(
            &mut self,
            request: impl tonic::IntoRequest<super::RevokeSessionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RevokeSessionResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.auth.AuthService/RevokeSession",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(GrpcMethod::new("cuba.iam.auth.AuthService", "RevokeSession"));
            self.inner.unary(req, path, codec).await
        }
        /// 开始 WebAuthn 注册
        pub async fn start_web_authn_registration(
            &mut self,
            request: impl tonic::IntoRequest<super::StartWebAuthnRegistrationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StartWebAuthnRegistrationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.auth.AuthService/StartWebAuthnRegistration",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "cuba.iam.auth.AuthService",
                        "StartWebAuthnRegistration",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 完成 WebAuthn 注册
        pub async fn finish_web_authn_registration(
            &mut self,
            request: impl tonic::IntoRequest<super::FinishWebAuthnRegistrationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FinishWebAuthnRegistrationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.auth.AuthService/FinishWebAuthnRegistration",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "cuba.iam.auth.AuthService",
                        "FinishWebAuthnRegistration",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 开始 WebAuthn 认证
        pub async fn start_web_authn_authentication(
            &mut self,
            request: impl tonic::IntoRequest<super::StartWebAuthnAuthenticationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StartWebAuthnAuthenticationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.auth.AuthService/StartWebAuthnAuthentication",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "cuba.iam.auth.AuthService",
                        "StartWebAuthnAuthentication",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 完成 WebAuthn 认证
        pub async fn finish_web_authn_authentication(
            &mut self,
            request: impl tonic::IntoRequest<super::FinishWebAuthnAuthenticationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FinishWebAuthnAuthenticationResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.auth.AuthService/FinishWebAuthnAuthentication",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "cuba.iam.auth.AuthService",
                        "FinishWebAuthnAuthentication",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 列出用户的 WebAuthn 凭证
        pub async fn list_web_authn_credentials(
            &mut self,
            request: impl tonic::IntoRequest<super::ListWebAuthnCredentialsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListWebAuthnCredentialsResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.auth.AuthService/ListWebAuthnCredentials",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "cuba.iam.auth.AuthService",
                        "ListWebAuthnCredentials",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
        /// 删除 WebAuthn 凭证
        pub async fn delete_web_authn_credential(
            &mut self,
            request: impl tonic::IntoRequest<super::DeleteWebAuthnCredentialRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteWebAuthnCredentialResponse>,
            tonic::Status,
        > {
            self.inner
                .ready()
                .await
                .map_err(|e| {
                    tonic::Status::unknown(
                        format!("Service was not ready: {}", e.into()),
                    )
                })?;
            let codec = tonic::codec::ProstCodec::default();
            let path = http::uri::PathAndQuery::from_static(
                "/cuba.iam.auth.AuthService/DeleteWebAuthnCredential",
            );
            let mut req = request.into_request();
            req.extensions_mut()
                .insert(
                    GrpcMethod::new(
                        "cuba.iam.auth.AuthService",
                        "DeleteWebAuthnCredential",
                    ),
                );
            self.inner.unary(req, path, codec).await
        }
    }
}
