// This file is @generated by prost-build.
/// 查询审计事件请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListEventsRequest {
    /// 租户 ID
    #[prost(string, tag = "1")]
    pub tenant_id: ::prost::alloc::string::String,
    /// 事件类型筛选 (可选)
    #[prost(string, tag = "2")]
    pub event_type: ::prost::alloc::string::String,
    /// 聚合类型筛选 (可选)
    #[prost(string, tag = "3")]
    pub aggregate_type: ::prost::alloc::string::String,
    /// 聚合 ID 筛选 (可选)
    #[prost(string, tag = "4")]
    pub aggregate_id: ::prost::alloc::string::String,
    /// 开始时间 (可选)
    #[prost(message, optional, tag = "5")]
    pub start_time: ::core::option::Option<::prost_types::Timestamp>,
    /// 结束时间 (可选)
    #[prost(message, optional, tag = "6")]
    pub end_time: ::core::option::Option<::prost_types::Timestamp>,
    /// 分页大小
    #[prost(int32, tag = "7")]
    pub page_size: i32,
    /// 分页令牌
    #[prost(string, tag = "8")]
    pub page_token: ::prost::alloc::string::String,
}
/// 查询审计事件响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListEventsResponse {
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<AuditEvent>,
    /// 下一页令牌
    #[prost(string, tag = "2")]
    pub next_page_token: ::prost::alloc::string::String,
    /// 总数
    #[prost(int32, tag = "3")]
    pub total_count: i32,
}
/// 获取用户审计历史请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserAuditHistoryRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 租户 ID
    #[prost(string, tag = "2")]
    pub tenant_id: ::prost::alloc::string::String,
    /// 分页大小
    #[prost(int32, tag = "3")]
    pub page_size: i32,
    /// 分页令牌
    #[prost(string, tag = "4")]
    pub page_token: ::prost::alloc::string::String,
}
/// 获取用户审计历史响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetUserAuditHistoryResponse {
    #[prost(message, repeated, tag = "1")]
    pub events: ::prost::alloc::vec::Vec<AuditEvent>,
    /// 下一页令牌
    #[prost(string, tag = "2")]
    pub next_page_token: ::prost::alloc::string::String,
}
/// 审计事件
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuditEvent {
    /// 事件 ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 事件类型
    #[prost(string, tag = "2")]
    pub event_type: ::prost::alloc::string::String,
    /// 聚合类型
    #[prost(string, tag = "3")]
    pub aggregate_type: ::prost::alloc::string::String,
    /// 聚合 ID
    #[prost(string, tag = "4")]
    pub aggregate_id: ::prost::alloc::string::String,
    /// 租户 ID
    #[prost(string, tag = "5")]
    pub tenant_id: ::prost::alloc::string::String,
    /// 事件数据 (JSON)
    #[prost(string, tag = "6")]
    pub payload: ::prost::alloc::string::String,
    /// 创建时间
    #[prost(message, optional, tag = "7")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// Generated server implementations.
pub mod audit_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AuditServiceServer.
    #[async_trait]
    pub trait AuditService: std::marker::Send + std::marker::Sync + 'static {
        /// 查询审计事件
        async fn list_events(
            &self,
            request: tonic::Request<super::ListEventsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListEventsResponse>,
            tonic::Status,
        >;
        /// 获取用户审计历史
        async fn get_user_audit_history(
            &self,
            request: tonic::Request<super::GetUserAuditHistoryRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetUserAuditHistoryResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct AuditServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> AuditServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for AuditServiceServer<T>
    where
        T: AuditService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/cuba.iam.audit.AuditService/ListEvents" => {
                    #[allow(non_camel_case_types)]
                    struct ListEventsSvc<T: AuditService>(pub Arc<T>);
                    impl<
                        T: AuditService,
                    > tonic::server::UnaryService<super::ListEventsRequest>
                    for ListEventsSvc<T> {
                        type Response = super::ListEventsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListEventsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuditService>::list_events(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListEventsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.audit.AuditService/GetUserAuditHistory" => {
                    #[allow(non_camel_case_types)]
                    struct GetUserAuditHistorySvc<T: AuditService>(pub Arc<T>);
                    impl<
                        T: AuditService,
                    > tonic::server::UnaryService<super::GetUserAuditHistoryRequest>
                    for GetUserAuditHistorySvc<T> {
                        type Response = super::GetUserAuditHistoryResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetUserAuditHistoryRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuditService>::get_user_audit_history(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetUserAuditHistorySvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for AuditServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "cuba.iam.audit.AuditService";
    impl<T> tonic::server::NamedService for AuditServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
