// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateClientRequest {
    /// Client 名称
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    /// 重定向 URI 列表
    #[prost(string, repeated, tag = "2")]
    pub redirect_uris: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 授权类型
    #[prost(string, repeated, tag = "3")]
    pub grant_types: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 权限范围
    #[prost(string, repeated, tag = "4")]
    pub scopes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// Client Secret（可选）
    #[prost(string, tag = "5")]
    pub client_secret: ::prost::alloc::string::String,
    /// 是否公开客户端
    #[prost(bool, tag = "6")]
    pub public_client: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct CreateClientResponse {
    /// Client ID
    #[prost(string, tag = "1")]
    pub client_id: ::prost::alloc::string::String,
    /// Client Secret
    #[prost(string, tag = "2")]
    pub client_secret: ::prost::alloc::string::String,
    /// Client 详情
    #[prost(message, optional, tag = "3")]
    pub client: ::core::option::Option<OAuthClient>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetClientRequest {
    /// Client ID
    #[prost(string, tag = "1")]
    pub client_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetClientResponse {
    /// Client 详情
    #[prost(message, optional, tag = "1")]
    pub client: ::core::option::Option<OAuthClient>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateClientRequest {
    /// Client ID
    #[prost(string, tag = "1")]
    pub client_id: ::prost::alloc::string::String,
    /// Client 名称
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// 重定向 URI 列表
    #[prost(string, repeated, tag = "3")]
    pub redirect_uris: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 授权类型
    #[prost(string, repeated, tag = "4")]
    pub grant_types: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 权限范围
    #[prost(string, repeated, tag = "5")]
    pub scopes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UpdateClientResponse {
    /// 更新后的 Client
    #[prost(message, optional, tag = "1")]
    pub client: ::core::option::Option<OAuthClient>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteClientRequest {
    /// Client ID
    #[prost(string, tag = "1")]
    pub client_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct ListClientsRequest {
    /// 页码
    #[prost(int32, tag = "1")]
    pub page: i32,
    /// 每页大小
    #[prost(int32, tag = "2")]
    pub page_size: i32,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListClientsResponse {
    /// Client 列表
    #[prost(message, repeated, tag = "1")]
    pub clients: ::prost::alloc::vec::Vec<OAuthClient>,
    /// 总数
    #[prost(int64, tag = "2")]
    pub total: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthorizeRequest {
    /// Client ID
    #[prost(string, tag = "1")]
    pub client_id: ::prost::alloc::string::String,
    /// 重定向 URI
    #[prost(string, tag = "2")]
    pub redirect_uri: ::prost::alloc::string::String,
    /// 响应类型（code）
    #[prost(string, tag = "3")]
    pub response_type: ::prost::alloc::string::String,
    /// 权限范围
    #[prost(string, tag = "4")]
    pub scope: ::prost::alloc::string::String,
    /// 状态参数
    #[prost(string, tag = "5")]
    pub state: ::prost::alloc::string::String,
    /// PKCE code challenge
    #[prost(string, tag = "6")]
    pub code_challenge: ::prost::alloc::string::String,
    /// PKCE 方法（S256/plain）
    #[prost(string, tag = "7")]
    pub code_challenge_method: ::prost::alloc::string::String,
    /// 用户 ID（已认证）
    #[prost(string, tag = "8")]
    pub user_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuthorizeResponse {
    /// 授权码
    #[prost(string, tag = "1")]
    pub code: ::prost::alloc::string::String,
    /// 状态参数
    #[prost(string, tag = "2")]
    pub state: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenRequest {
    /// 授权类型
    #[prost(string, tag = "1")]
    pub grant_type: ::prost::alloc::string::String,
    /// 授权码（authorization_code）
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
    /// 重定向 URI
    #[prost(string, tag = "3")]
    pub redirect_uri: ::prost::alloc::string::String,
    /// Client ID
    #[prost(string, tag = "4")]
    pub client_id: ::prost::alloc::string::String,
    /// Client Secret
    #[prost(string, tag = "5")]
    pub client_secret: ::prost::alloc::string::String,
    /// PKCE code verifier
    #[prost(string, tag = "6")]
    pub code_verifier: ::prost::alloc::string::String,
    /// Refresh Token（refresh_token）
    #[prost(string, tag = "7")]
    pub refresh_token: ::prost::alloc::string::String,
    /// 权限范围
    #[prost(string, tag = "8")]
    pub scope: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TokenResponse {
    /// Access Token
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// Token 类型（Bearer）
    #[prost(string, tag = "2")]
    pub token_type: ::prost::alloc::string::String,
    /// 过期时间（秒）
    #[prost(int64, tag = "3")]
    pub expires_in: i64,
    /// Refresh Token
    #[prost(string, tag = "4")]
    pub refresh_token: ::prost::alloc::string::String,
    /// 权限范围
    #[prost(string, tag = "5")]
    pub scope: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RefreshTokenRequest {
    /// Refresh Token
    #[prost(string, tag = "1")]
    pub refresh_token: ::prost::alloc::string::String,
    /// Client ID
    #[prost(string, tag = "2")]
    pub client_id: ::prost::alloc::string::String,
    /// Client Secret
    #[prost(string, tag = "3")]
    pub client_secret: ::prost::alloc::string::String,
    /// 权限范围
    #[prost(string, tag = "4")]
    pub scope: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevokeTokenRequest {
    /// Token
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    /// Token 类型提示
    #[prost(string, tag = "2")]
    pub token_type_hint: ::prost::alloc::string::String,
    /// Client ID
    #[prost(string, tag = "3")]
    pub client_id: ::prost::alloc::string::String,
    /// Client Secret
    #[prost(string, tag = "4")]
    pub client_secret: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IntrospectTokenRequest {
    /// Token
    #[prost(string, tag = "1")]
    pub token: ::prost::alloc::string::String,
    /// Token 类型提示
    #[prost(string, tag = "2")]
    pub token_type_hint: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct IntrospectTokenResponse {
    /// 是否有效
    #[prost(bool, tag = "1")]
    pub active: bool,
    /// 权限范围
    #[prost(string, tag = "2")]
    pub scope: ::prost::alloc::string::String,
    /// Client ID
    #[prost(string, tag = "3")]
    pub client_id: ::prost::alloc::string::String,
    /// 用户名
    #[prost(string, tag = "4")]
    pub username: ::prost::alloc::string::String,
    /// Token 类型
    #[prost(string, tag = "5")]
    pub token_type: ::prost::alloc::string::String,
    /// 过期时间
    #[prost(int64, tag = "6")]
    pub exp: i64,
    /// 签发时间
    #[prost(int64, tag = "7")]
    pub iat: i64,
    /// 主体（用户 ID）
    #[prost(string, tag = "8")]
    pub sub: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct OAuthClient {
    /// Client ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// Client 名称
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// 重定向 URI 列表
    #[prost(string, repeated, tag = "3")]
    pub redirect_uris: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 授权类型
    #[prost(string, repeated, tag = "4")]
    pub grant_types: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 权限范围
    #[prost(string, repeated, tag = "5")]
    pub scopes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 是否公开客户端
    #[prost(bool, tag = "6")]
    pub public_client: bool,
    /// 租户 ID
    #[prost(string, tag = "7")]
    pub tenant_id: ::prost::alloc::string::String,
    /// 创建时间
    #[prost(message, optional, tag = "8")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// Generated server implementations.
pub mod o_auth_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with OAuthServiceServer.
    #[async_trait]
    pub trait OAuthService: std::marker::Send + std::marker::Sync + 'static {
        /// 创建 OAuth Client
        async fn create_client(
            &self,
            request: tonic::Request<super::CreateClientRequest>,
        ) -> std::result::Result<
            tonic::Response<super::CreateClientResponse>,
            tonic::Status,
        >;
        /// 获取 OAuth Client
        async fn get_client(
            &self,
            request: tonic::Request<super::GetClientRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetClientResponse>,
            tonic::Status,
        >;
        /// 更新 OAuth Client
        async fn update_client(
            &self,
            request: tonic::Request<super::UpdateClientRequest>,
        ) -> std::result::Result<
            tonic::Response<super::UpdateClientResponse>,
            tonic::Status,
        >;
        /// 删除 OAuth Client
        async fn delete_client(
            &self,
            request: tonic::Request<super::DeleteClientRequest>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status>;
        /// 列出 OAuth Clients
        async fn list_clients(
            &self,
            request: tonic::Request<super::ListClientsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListClientsResponse>,
            tonic::Status,
        >;
        /// 授权请求（返回授权码）
        async fn authorize(
            &self,
            request: tonic::Request<super::AuthorizeRequest>,
        ) -> std::result::Result<
            tonic::Response<super::AuthorizeResponse>,
            tonic::Status,
        >;
        /// Token 请求（授权码换 Token）
        async fn token(
            &self,
            request: tonic::Request<super::TokenRequest>,
        ) -> std::result::Result<tonic::Response<super::TokenResponse>, tonic::Status>;
        /// 刷新 Token
        async fn refresh_token(
            &self,
            request: tonic::Request<super::RefreshTokenRequest>,
        ) -> std::result::Result<tonic::Response<super::TokenResponse>, tonic::Status>;
        /// 撤销 Token
        async fn revoke_token(
            &self,
            request: tonic::Request<super::RevokeTokenRequest>,
        ) -> std::result::Result<tonic::Response<()>, tonic::Status>;
        /// 验证 Token
        async fn introspect_token(
            &self,
            request: tonic::Request<super::IntrospectTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::IntrospectTokenResponse>,
            tonic::Status,
        >;
    }
    /// OAuth2 授权服务
    #[derive(Debug)]
    pub struct OAuthServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> OAuthServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for OAuthServiceServer<T>
    where
        T: OAuthService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/cuba.iam.oauth.v1.OAuthService/CreateClient" => {
                    #[allow(non_camel_case_types)]
                    struct CreateClientSvc<T: OAuthService>(pub Arc<T>);
                    impl<
                        T: OAuthService,
                    > tonic::server::UnaryService<super::CreateClientRequest>
                    for CreateClientSvc<T> {
                        type Response = super::CreateClientResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::CreateClientRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OAuthService>::create_client(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = CreateClientSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.oauth.v1.OAuthService/GetClient" => {
                    #[allow(non_camel_case_types)]
                    struct GetClientSvc<T: OAuthService>(pub Arc<T>);
                    impl<
                        T: OAuthService,
                    > tonic::server::UnaryService<super::GetClientRequest>
                    for GetClientSvc<T> {
                        type Response = super::GetClientResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetClientRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OAuthService>::get_client(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetClientSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.oauth.v1.OAuthService/UpdateClient" => {
                    #[allow(non_camel_case_types)]
                    struct UpdateClientSvc<T: OAuthService>(pub Arc<T>);
                    impl<
                        T: OAuthService,
                    > tonic::server::UnaryService<super::UpdateClientRequest>
                    for UpdateClientSvc<T> {
                        type Response = super::UpdateClientResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::UpdateClientRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OAuthService>::update_client(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = UpdateClientSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.oauth.v1.OAuthService/DeleteClient" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteClientSvc<T: OAuthService>(pub Arc<T>);
                    impl<
                        T: OAuthService,
                    > tonic::server::UnaryService<super::DeleteClientRequest>
                    for DeleteClientSvc<T> {
                        type Response = ();
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::DeleteClientRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OAuthService>::delete_client(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteClientSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.oauth.v1.OAuthService/ListClients" => {
                    #[allow(non_camel_case_types)]
                    struct ListClientsSvc<T: OAuthService>(pub Arc<T>);
                    impl<
                        T: OAuthService,
                    > tonic::server::UnaryService<super::ListClientsRequest>
                    for ListClientsSvc<T> {
                        type Response = super::ListClientsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ListClientsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OAuthService>::list_clients(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListClientsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.oauth.v1.OAuthService/Authorize" => {
                    #[allow(non_camel_case_types)]
                    struct AuthorizeSvc<T: OAuthService>(pub Arc<T>);
                    impl<
                        T: OAuthService,
                    > tonic::server::UnaryService<super::AuthorizeRequest>
                    for AuthorizeSvc<T> {
                        type Response = super::AuthorizeResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::AuthorizeRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OAuthService>::authorize(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = AuthorizeSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.oauth.v1.OAuthService/Token" => {
                    #[allow(non_camel_case_types)]
                    struct TokenSvc<T: OAuthService>(pub Arc<T>);
                    impl<
                        T: OAuthService,
                    > tonic::server::UnaryService<super::TokenRequest> for TokenSvc<T> {
                        type Response = super::TokenResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::TokenRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OAuthService>::token(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = TokenSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.oauth.v1.OAuthService/RefreshToken" => {
                    #[allow(non_camel_case_types)]
                    struct RefreshTokenSvc<T: OAuthService>(pub Arc<T>);
                    impl<
                        T: OAuthService,
                    > tonic::server::UnaryService<super::RefreshTokenRequest>
                    for RefreshTokenSvc<T> {
                        type Response = super::TokenResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RefreshTokenRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OAuthService>::refresh_token(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RefreshTokenSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.oauth.v1.OAuthService/RevokeToken" => {
                    #[allow(non_camel_case_types)]
                    struct RevokeTokenSvc<T: OAuthService>(pub Arc<T>);
                    impl<
                        T: OAuthService,
                    > tonic::server::UnaryService<super::RevokeTokenRequest>
                    for RevokeTokenSvc<T> {
                        type Response = ();
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RevokeTokenRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OAuthService>::revoke_token(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RevokeTokenSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/cuba.iam.oauth.v1.OAuthService/IntrospectToken" => {
                    #[allow(non_camel_case_types)]
                    struct IntrospectTokenSvc<T: OAuthService>(pub Arc<T>);
                    impl<
                        T: OAuthService,
                    > tonic::server::UnaryService<super::IntrospectTokenRequest>
                    for IntrospectTokenSvc<T> {
                        type Response = super::IntrospectTokenResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::IntrospectTokenRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as OAuthService>::introspect_token(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = IntrospectTokenSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for OAuthServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "cuba.iam.oauth.v1.OAuthService";
    impl<T> tonic::server::NamedService for OAuthServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
