// This file is @generated by prost-build.
/// 登录请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginRequest {
    /// 用户名或邮箱
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    /// 密码
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
    /// 租户 ID
    #[prost(string, tag = "3")]
    pub tenant_id: ::prost::alloc::string::String,
    /// 设备信息
    #[prost(string, tag = "4")]
    pub device_info: ::prost::alloc::string::String,
    /// IP 地址
    #[prost(string, tag = "5")]
    pub ip_address: ::prost::alloc::string::String,
}
/// 登录响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LoginResponse {
    /// 访问令牌
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// 刷新令牌
    #[prost(string, tag = "2")]
    pub refresh_token: ::prost::alloc::string::String,
    /// 过期时间（秒）
    #[prost(int64, tag = "3")]
    pub expires_in: i64,
    /// 令牌类型
    #[prost(string, tag = "4")]
    pub token_type: ::prost::alloc::string::String,
    /// 用户信息
    #[prost(message, optional, tag = "5")]
    pub user: ::core::option::Option<User>,
    /// 是否需要 2FA
    #[prost(bool, tag = "6")]
    pub require_2fa: bool,
    /// 会话 ID（用于 2FA）
    #[prost(string, tag = "7")]
    pub session_id: ::prost::alloc::string::String,
}
/// 登出请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct LogoutRequest {
    /// 访问令牌
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// 是否登出所有设备
    #[prost(bool, tag = "2")]
    pub logout_all_devices: bool,
}
/// 登出响应
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct LogoutResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
/// 刷新令牌请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RefreshTokenRequest {
    #[prost(string, tag = "1")]
    pub refresh_token: ::prost::alloc::string::String,
}
/// 刷新令牌响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RefreshTokenResponse {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub refresh_token: ::prost::alloc::string::String,
    #[prost(int64, tag = "3")]
    pub expires_in: i64,
}
/// 验证令牌请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidateTokenRequest {
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
}
/// 验证令牌响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValidateTokenResponse {
    #[prost(bool, tag = "1")]
    pub valid: bool,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub permissions: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(message, optional, tag = "5")]
    pub expires_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// 修改密码请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChangePasswordRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub old_password: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub new_password: ::prost::alloc::string::String,
}
/// 修改密码响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ChangePasswordResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// 请求重置密码请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestPasswordResetRequest {
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub tenant_id: ::prost::alloc::string::String,
}
/// 请求重置密码响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestPasswordResetResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// 重置密码请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResetPasswordRequest {
    #[prost(string, tag = "1")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub reset_token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub new_password: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub tenant_id: ::prost::alloc::string::String,
}
/// 重置密码响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ResetPasswordResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// 启用 2FA 请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Enable2FaRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// TOTP, SMS, EMAIL
    #[prost(string, tag = "2")]
    pub method: ::prost::alloc::string::String,
    /// 验证码（可选，用于确认启用）
    #[prost(string, tag = "3")]
    pub verification_code: ::prost::alloc::string::String,
}
/// 启用 2FA 响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Enable2FaResponse {
    /// TOTP secret（Base32 编码）
    #[prost(string, tag = "1")]
    pub secret: ::prost::alloc::string::String,
    /// QR 码 URL
    #[prost(string, tag = "2")]
    pub qr_code_url: ::prost::alloc::string::String,
    /// 备份码（仅首次返回）
    #[prost(string, repeated, tag = "3")]
    pub backup_codes: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 是否已启用（需要验证码确认）
    #[prost(bool, tag = "4")]
    pub enabled: bool,
}
/// 禁用 2FA 请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Disable2FaRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 密码验证
    #[prost(string, tag = "2")]
    pub password: ::prost::alloc::string::String,
}
/// 禁用 2FA 响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Disable2FaResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// 验证 2FA 请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Verify2FaRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub code: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub tenant_id: ::prost::alloc::string::String,
}
/// 验证 2FA 响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Verify2FaResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub access_token: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub refresh_token: ::prost::alloc::string::String,
    /// 过期时间（秒）
    #[prost(int64, tag = "4")]
    pub expires_in: i64,
}
/// 获取活跃会话请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetActiveSessionsRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
/// 获取活跃会话响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GetActiveSessionsResponse {
    #[prost(message, repeated, tag = "1")]
    pub sessions: ::prost::alloc::vec::Vec<Session>,
}
/// 撤销会话请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RevokeSessionRequest {
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub session_id: ::prost::alloc::string::String,
}
/// 撤销会话响应
#[derive(Clone, Copy, PartialEq, ::prost::Message)]
pub struct RevokeSessionResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
}
/// 开始 WebAuthn 注册请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartWebAuthnRegistrationRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 凭证名称（如 "YubiKey 5"）
    #[prost(string, tag = "2")]
    pub credential_name: ::prost::alloc::string::String,
}
/// 开始 WebAuthn 注册响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartWebAuthnRegistrationResponse {
    /// 挑战（Base64 编码）
    #[prost(string, tag = "1")]
    pub challenge: ::prost::alloc::string::String,
    /// Relying Party ID
    #[prost(string, tag = "2")]
    pub rp_id: ::prost::alloc::string::String,
    /// Relying Party 名称
    #[prost(string, tag = "3")]
    pub rp_name: ::prost::alloc::string::String,
    /// 用户 ID（Base64 编码）
    #[prost(string, tag = "4")]
    pub user_id: ::prost::alloc::string::String,
    /// 用户名
    #[prost(string, tag = "5")]
    pub user_name: ::prost::alloc::string::String,
    /// 用户显示名称
    #[prost(string, tag = "6")]
    pub user_display_name: ::prost::alloc::string::String,
    /// 排除的凭证 ID（Base64 编码）
    #[prost(string, repeated, tag = "7")]
    pub exclude_credentials: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 注册状态（用于完成注册）
    #[prost(string, tag = "8")]
    pub registration_state: ::prost::alloc::string::String,
}
/// 完成 WebAuthn 注册请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FinishWebAuthnRegistrationRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 凭证名称
    #[prost(string, tag = "2")]
    pub credential_name: ::prost::alloc::string::String,
    /// 注册状态
    #[prost(string, tag = "3")]
    pub registration_state: ::prost::alloc::string::String,
    /// 凭证响应（JSON 格式）
    #[prost(string, tag = "4")]
    pub credential_response: ::prost::alloc::string::String,
}
/// 完成 WebAuthn 注册响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FinishWebAuthnRegistrationResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    /// 凭证 ID
    #[prost(string, tag = "2")]
    pub credential_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub message: ::prost::alloc::string::String,
}
/// 开始 WebAuthn 认证请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartWebAuthnAuthenticationRequest {
    /// 用户名或邮箱
    #[prost(string, tag = "1")]
    pub username: ::prost::alloc::string::String,
    /// 租户 ID
    #[prost(string, tag = "2")]
    pub tenant_id: ::prost::alloc::string::String,
}
/// 开始 WebAuthn 认证响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StartWebAuthnAuthenticationResponse {
    /// 挑战（Base64 编码）
    #[prost(string, tag = "1")]
    pub challenge: ::prost::alloc::string::String,
    /// Relying Party ID
    #[prost(string, tag = "2")]
    pub rp_id: ::prost::alloc::string::String,
    /// 允许的凭证 ID（Base64 编码）
    #[prost(string, repeated, tag = "3")]
    pub allow_credentials: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 认证状态（用于完成认证）
    #[prost(string, tag = "4")]
    pub authentication_state: ::prost::alloc::string::String,
    /// 用户 ID（用于客户端）
    #[prost(string, tag = "5")]
    pub user_id: ::prost::alloc::string::String,
}
/// 完成 WebAuthn 认证请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FinishWebAuthnAuthenticationRequest {
    /// 认证状态
    #[prost(string, tag = "1")]
    pub authentication_state: ::prost::alloc::string::String,
    /// 凭证响应（JSON 格式）
    #[prost(string, tag = "2")]
    pub credential_response: ::prost::alloc::string::String,
    /// 设备信息
    #[prost(string, tag = "3")]
    pub device_info: ::prost::alloc::string::String,
    /// IP 地址
    #[prost(string, tag = "4")]
    pub ip_address: ::prost::alloc::string::String,
    /// 租户 ID
    #[prost(string, tag = "5")]
    pub tenant_id: ::prost::alloc::string::String,
}
/// 完成 WebAuthn 认证响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct FinishWebAuthnAuthenticationResponse {
    /// 访问令牌
    #[prost(string, tag = "1")]
    pub access_token: ::prost::alloc::string::String,
    /// 刷新令牌
    #[prost(string, tag = "2")]
    pub refresh_token: ::prost::alloc::string::String,
    /// 过期时间（秒）
    #[prost(int64, tag = "3")]
    pub expires_in: i64,
    /// 令牌类型
    #[prost(string, tag = "4")]
    pub token_type: ::prost::alloc::string::String,
    /// 用户信息
    #[prost(message, optional, tag = "5")]
    pub user: ::core::option::Option<User>,
}
/// 列出 WebAuthn 凭证请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListWebAuthnCredentialsRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
}
/// 列出 WebAuthn 凭证响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListWebAuthnCredentialsResponse {
    #[prost(message, repeated, tag = "1")]
    pub credentials: ::prost::alloc::vec::Vec<WebAuthnCredential>,
}
/// 删除 WebAuthn 凭证请求
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteWebAuthnCredentialRequest {
    /// 用户 ID
    #[prost(string, tag = "1")]
    pub user_id: ::prost::alloc::string::String,
    /// 凭证 ID
    #[prost(string, tag = "2")]
    pub credential_id: ::prost::alloc::string::String,
}
/// 删除 WebAuthn 凭证响应
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DeleteWebAuthnCredentialResponse {
    #[prost(bool, tag = "1")]
    pub success: bool,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
/// WebAuthn 凭证
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct WebAuthnCredential {
    /// 凭证 ID
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    /// 凭证名称
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    /// 传输方式（usb, nfc, ble, internal）
    #[prost(string, repeated, tag = "3")]
    pub transports: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    /// 是否可备份
    #[prost(bool, tag = "4")]
    pub backup_eligible: bool,
    /// 是否已备份
    #[prost(bool, tag = "5")]
    pub backup_state: bool,
    /// 创建时间
    #[prost(message, optional, tag = "6")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    /// 最后使用时间
    #[prost(message, optional, tag = "7")]
    pub last_used_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// 用户
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct User {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub username: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub phone: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub avatar_url: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "8")]
    pub role_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "9")]
    pub status: ::prost::alloc::string::String,
    #[prost(string, tag = "10")]
    pub language: ::prost::alloc::string::String,
    #[prost(string, tag = "11")]
    pub timezone: ::prost::alloc::string::String,
    #[prost(bool, tag = "12")]
    pub two_factor_enabled: bool,
    #[prost(message, optional, tag = "13")]
    pub last_login_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "14")]
    pub audit_info: ::core::option::Option<AuditInfo>,
}
/// 会话
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Session {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub device_info: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub ip_address: ::prost::alloc::string::String,
    #[prost(string, tag = "5")]
    pub user_agent: ::prost::alloc::string::String,
    #[prost(bool, tag = "6")]
    pub is_current: bool,
    #[prost(message, optional, tag = "7")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "8")]
    pub expires_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag = "9")]
    pub last_activity_at: ::core::option::Option<::prost_types::Timestamp>,
}
/// 审计信息
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AuditInfo {
    #[prost(message, optional, tag = "1")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "2")]
    pub created_by: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "3")]
    pub updated_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(string, tag = "4")]
    pub updated_by: ::prost::alloc::string::String,
}
/// Generated server implementations.
pub mod auth_service_server {
    #![allow(
        unused_variables,
        dead_code,
        missing_docs,
        clippy::wildcard_imports,
        clippy::let_unit_value,
    )]
    use tonic::codegen::*;
    /// Generated trait containing gRPC methods that should be implemented for use with AuthServiceServer.
    #[async_trait]
    pub trait AuthService: std::marker::Send + std::marker::Sync + 'static {
        /// 用户登录
        async fn login(
            &self,
            request: tonic::Request<super::LoginRequest>,
        ) -> std::result::Result<tonic::Response<super::LoginResponse>, tonic::Status>;
        /// 用户登出
        async fn logout(
            &self,
            request: tonic::Request<super::LogoutRequest>,
        ) -> std::result::Result<tonic::Response<super::LogoutResponse>, tonic::Status>;
        /// 刷新令牌
        async fn refresh_token(
            &self,
            request: tonic::Request<super::RefreshTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RefreshTokenResponse>,
            tonic::Status,
        >;
        /// 验证令牌
        async fn validate_token(
            &self,
            request: tonic::Request<super::ValidateTokenRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ValidateTokenResponse>,
            tonic::Status,
        >;
        /// 修改密码
        async fn change_password(
            &self,
            request: tonic::Request<super::ChangePasswordRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ChangePasswordResponse>,
            tonic::Status,
        >;
        /// 请求重置密码
        async fn request_password_reset(
            &self,
            request: tonic::Request<super::RequestPasswordResetRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RequestPasswordResetResponse>,
            tonic::Status,
        >;
        /// 重置密码
        async fn reset_password(
            &self,
            request: tonic::Request<super::ResetPasswordRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ResetPasswordResponse>,
            tonic::Status,
        >;
        /// 启用 2FA
        async fn enable2_fa(
            &self,
            request: tonic::Request<super::Enable2FaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::Enable2FaResponse>,
            tonic::Status,
        >;
        /// 禁用 2FA
        async fn disable2_fa(
            &self,
            request: tonic::Request<super::Disable2FaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::Disable2FaResponse>,
            tonic::Status,
        >;
        /// 验证 2FA
        async fn verify2_fa(
            &self,
            request: tonic::Request<super::Verify2FaRequest>,
        ) -> std::result::Result<
            tonic::Response<super::Verify2FaResponse>,
            tonic::Status,
        >;
        /// 获取活跃会话
        async fn get_active_sessions(
            &self,
            request: tonic::Request<super::GetActiveSessionsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::GetActiveSessionsResponse>,
            tonic::Status,
        >;
        /// 撤销会话
        async fn revoke_session(
            &self,
            request: tonic::Request<super::RevokeSessionRequest>,
        ) -> std::result::Result<
            tonic::Response<super::RevokeSessionResponse>,
            tonic::Status,
        >;
        /// 开始 WebAuthn 注册
        async fn start_web_authn_registration(
            &self,
            request: tonic::Request<super::StartWebAuthnRegistrationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StartWebAuthnRegistrationResponse>,
            tonic::Status,
        >;
        /// 完成 WebAuthn 注册
        async fn finish_web_authn_registration(
            &self,
            request: tonic::Request<super::FinishWebAuthnRegistrationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FinishWebAuthnRegistrationResponse>,
            tonic::Status,
        >;
        /// 开始 WebAuthn 认证
        async fn start_web_authn_authentication(
            &self,
            request: tonic::Request<super::StartWebAuthnAuthenticationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::StartWebAuthnAuthenticationResponse>,
            tonic::Status,
        >;
        /// 完成 WebAuthn 认证
        async fn finish_web_authn_authentication(
            &self,
            request: tonic::Request<super::FinishWebAuthnAuthenticationRequest>,
        ) -> std::result::Result<
            tonic::Response<super::FinishWebAuthnAuthenticationResponse>,
            tonic::Status,
        >;
        /// 列出用户的 WebAuthn 凭证
        async fn list_web_authn_credentials(
            &self,
            request: tonic::Request<super::ListWebAuthnCredentialsRequest>,
        ) -> std::result::Result<
            tonic::Response<super::ListWebAuthnCredentialsResponse>,
            tonic::Status,
        >;
        /// 删除 WebAuthn 凭证
        async fn delete_web_authn_credential(
            &self,
            request: tonic::Request<super::DeleteWebAuthnCredentialRequest>,
        ) -> std::result::Result<
            tonic::Response<super::DeleteWebAuthnCredentialResponse>,
            tonic::Status,
        >;
    }
    #[derive(Debug)]
    pub struct AuthServiceServer<T> {
        inner: Arc<T>,
        accept_compression_encodings: EnabledCompressionEncodings,
        send_compression_encodings: EnabledCompressionEncodings,
        max_decoding_message_size: Option<usize>,
        max_encoding_message_size: Option<usize>,
    }
    impl<T> AuthServiceServer<T> {
        pub fn new(inner: T) -> Self {
            Self::from_arc(Arc::new(inner))
        }
        pub fn from_arc(inner: Arc<T>) -> Self {
            Self {
                inner,
                accept_compression_encodings: Default::default(),
                send_compression_encodings: Default::default(),
                max_decoding_message_size: None,
                max_encoding_message_size: None,
            }
        }
        pub fn with_interceptor<F>(
            inner: T,
            interceptor: F,
        ) -> InterceptedService<Self, F>
        where
            F: tonic::service::Interceptor,
        {
            InterceptedService::new(Self::new(inner), interceptor)
        }
        /// Enable decompressing requests with the given encoding.
        #[must_use]
        pub fn accept_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.accept_compression_encodings.enable(encoding);
            self
        }
        /// Compress responses with the given encoding, if the client supports it.
        #[must_use]
        pub fn send_compressed(mut self, encoding: CompressionEncoding) -> Self {
            self.send_compression_encodings.enable(encoding);
            self
        }
        /// Limits the maximum size of a decoded message.
        ///
        /// Default: `4MB`
        #[must_use]
        pub fn max_decoding_message_size(mut self, limit: usize) -> Self {
            self.max_decoding_message_size = Some(limit);
            self
        }
        /// Limits the maximum size of an encoded message.
        ///
        /// Default: `usize::MAX`
        #[must_use]
        pub fn max_encoding_message_size(mut self, limit: usize) -> Self {
            self.max_encoding_message_size = Some(limit);
            self
        }
    }
    impl<T, B> tonic::codegen::Service<http::Request<B>> for AuthServiceServer<T>
    where
        T: AuthService,
        B: Body + std::marker::Send + 'static,
        B::Error: Into<StdError> + std::marker::Send + 'static,
    {
        type Response = http::Response<tonic::body::Body>;
        type Error = std::convert::Infallible;
        type Future = BoxFuture<Self::Response, Self::Error>;
        fn poll_ready(
            &mut self,
            _cx: &mut Context<'_>,
        ) -> Poll<std::result::Result<(), Self::Error>> {
            Poll::Ready(Ok(()))
        }
        fn call(&mut self, req: http::Request<B>) -> Self::Future {
            match req.uri().path() {
                "/iam.auth.v1.AuthService/Login" => {
                    #[allow(non_camel_case_types)]
                    struct LoginSvc<T: AuthService>(pub Arc<T>);
                    impl<T: AuthService> tonic::server::UnaryService<super::LoginRequest>
                    for LoginSvc<T> {
                        type Response = super::LoginResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LoginRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuthService>::login(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LoginSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/iam.auth.v1.AuthService/Logout" => {
                    #[allow(non_camel_case_types)]
                    struct LogoutSvc<T: AuthService>(pub Arc<T>);
                    impl<
                        T: AuthService,
                    > tonic::server::UnaryService<super::LogoutRequest>
                    for LogoutSvc<T> {
                        type Response = super::LogoutResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::LogoutRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuthService>::logout(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = LogoutSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/iam.auth.v1.AuthService/RefreshToken" => {
                    #[allow(non_camel_case_types)]
                    struct RefreshTokenSvc<T: AuthService>(pub Arc<T>);
                    impl<
                        T: AuthService,
                    > tonic::server::UnaryService<super::RefreshTokenRequest>
                    for RefreshTokenSvc<T> {
                        type Response = super::RefreshTokenResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RefreshTokenRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuthService>::refresh_token(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RefreshTokenSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/iam.auth.v1.AuthService/ValidateToken" => {
                    #[allow(non_camel_case_types)]
                    struct ValidateTokenSvc<T: AuthService>(pub Arc<T>);
                    impl<
                        T: AuthService,
                    > tonic::server::UnaryService<super::ValidateTokenRequest>
                    for ValidateTokenSvc<T> {
                        type Response = super::ValidateTokenResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ValidateTokenRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuthService>::validate_token(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ValidateTokenSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/iam.auth.v1.AuthService/ChangePassword" => {
                    #[allow(non_camel_case_types)]
                    struct ChangePasswordSvc<T: AuthService>(pub Arc<T>);
                    impl<
                        T: AuthService,
                    > tonic::server::UnaryService<super::ChangePasswordRequest>
                    for ChangePasswordSvc<T> {
                        type Response = super::ChangePasswordResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ChangePasswordRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuthService>::change_password(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ChangePasswordSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/iam.auth.v1.AuthService/RequestPasswordReset" => {
                    #[allow(non_camel_case_types)]
                    struct RequestPasswordResetSvc<T: AuthService>(pub Arc<T>);
                    impl<
                        T: AuthService,
                    > tonic::server::UnaryService<super::RequestPasswordResetRequest>
                    for RequestPasswordResetSvc<T> {
                        type Response = super::RequestPasswordResetResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RequestPasswordResetRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuthService>::request_password_reset(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RequestPasswordResetSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/iam.auth.v1.AuthService/ResetPassword" => {
                    #[allow(non_camel_case_types)]
                    struct ResetPasswordSvc<T: AuthService>(pub Arc<T>);
                    impl<
                        T: AuthService,
                    > tonic::server::UnaryService<super::ResetPasswordRequest>
                    for ResetPasswordSvc<T> {
                        type Response = super::ResetPasswordResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::ResetPasswordRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuthService>::reset_password(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ResetPasswordSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/iam.auth.v1.AuthService/Enable2FA" => {
                    #[allow(non_camel_case_types)]
                    struct Enable2FASvc<T: AuthService>(pub Arc<T>);
                    impl<
                        T: AuthService,
                    > tonic::server::UnaryService<super::Enable2FaRequest>
                    for Enable2FASvc<T> {
                        type Response = super::Enable2FaResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::Enable2FaRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuthService>::enable2_fa(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = Enable2FASvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/iam.auth.v1.AuthService/Disable2FA" => {
                    #[allow(non_camel_case_types)]
                    struct Disable2FASvc<T: AuthService>(pub Arc<T>);
                    impl<
                        T: AuthService,
                    > tonic::server::UnaryService<super::Disable2FaRequest>
                    for Disable2FASvc<T> {
                        type Response = super::Disable2FaResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::Disable2FaRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuthService>::disable2_fa(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = Disable2FASvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/iam.auth.v1.AuthService/Verify2FA" => {
                    #[allow(non_camel_case_types)]
                    struct Verify2FASvc<T: AuthService>(pub Arc<T>);
                    impl<
                        T: AuthService,
                    > tonic::server::UnaryService<super::Verify2FaRequest>
                    for Verify2FASvc<T> {
                        type Response = super::Verify2FaResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::Verify2FaRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuthService>::verify2_fa(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = Verify2FASvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/iam.auth.v1.AuthService/GetActiveSessions" => {
                    #[allow(non_camel_case_types)]
                    struct GetActiveSessionsSvc<T: AuthService>(pub Arc<T>);
                    impl<
                        T: AuthService,
                    > tonic::server::UnaryService<super::GetActiveSessionsRequest>
                    for GetActiveSessionsSvc<T> {
                        type Response = super::GetActiveSessionsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::GetActiveSessionsRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuthService>::get_active_sessions(&inner, request)
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = GetActiveSessionsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/iam.auth.v1.AuthService/RevokeSession" => {
                    #[allow(non_camel_case_types)]
                    struct RevokeSessionSvc<T: AuthService>(pub Arc<T>);
                    impl<
                        T: AuthService,
                    > tonic::server::UnaryService<super::RevokeSessionRequest>
                    for RevokeSessionSvc<T> {
                        type Response = super::RevokeSessionResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<super::RevokeSessionRequest>,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuthService>::revoke_session(&inner, request).await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = RevokeSessionSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/iam.auth.v1.AuthService/StartWebAuthnRegistration" => {
                    #[allow(non_camel_case_types)]
                    struct StartWebAuthnRegistrationSvc<T: AuthService>(pub Arc<T>);
                    impl<
                        T: AuthService,
                    > tonic::server::UnaryService<
                        super::StartWebAuthnRegistrationRequest,
                    > for StartWebAuthnRegistrationSvc<T> {
                        type Response = super::StartWebAuthnRegistrationResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::StartWebAuthnRegistrationRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuthService>::start_web_authn_registration(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StartWebAuthnRegistrationSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/iam.auth.v1.AuthService/FinishWebAuthnRegistration" => {
                    #[allow(non_camel_case_types)]
                    struct FinishWebAuthnRegistrationSvc<T: AuthService>(pub Arc<T>);
                    impl<
                        T: AuthService,
                    > tonic::server::UnaryService<
                        super::FinishWebAuthnRegistrationRequest,
                    > for FinishWebAuthnRegistrationSvc<T> {
                        type Response = super::FinishWebAuthnRegistrationResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::FinishWebAuthnRegistrationRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuthService>::finish_web_authn_registration(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FinishWebAuthnRegistrationSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/iam.auth.v1.AuthService/StartWebAuthnAuthentication" => {
                    #[allow(non_camel_case_types)]
                    struct StartWebAuthnAuthenticationSvc<T: AuthService>(pub Arc<T>);
                    impl<
                        T: AuthService,
                    > tonic::server::UnaryService<
                        super::StartWebAuthnAuthenticationRequest,
                    > for StartWebAuthnAuthenticationSvc<T> {
                        type Response = super::StartWebAuthnAuthenticationResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::StartWebAuthnAuthenticationRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuthService>::start_web_authn_authentication(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = StartWebAuthnAuthenticationSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/iam.auth.v1.AuthService/FinishWebAuthnAuthentication" => {
                    #[allow(non_camel_case_types)]
                    struct FinishWebAuthnAuthenticationSvc<T: AuthService>(pub Arc<T>);
                    impl<
                        T: AuthService,
                    > tonic::server::UnaryService<
                        super::FinishWebAuthnAuthenticationRequest,
                    > for FinishWebAuthnAuthenticationSvc<T> {
                        type Response = super::FinishWebAuthnAuthenticationResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::FinishWebAuthnAuthenticationRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuthService>::finish_web_authn_authentication(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = FinishWebAuthnAuthenticationSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/iam.auth.v1.AuthService/ListWebAuthnCredentials" => {
                    #[allow(non_camel_case_types)]
                    struct ListWebAuthnCredentialsSvc<T: AuthService>(pub Arc<T>);
                    impl<
                        T: AuthService,
                    > tonic::server::UnaryService<super::ListWebAuthnCredentialsRequest>
                    for ListWebAuthnCredentialsSvc<T> {
                        type Response = super::ListWebAuthnCredentialsResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::ListWebAuthnCredentialsRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuthService>::list_web_authn_credentials(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = ListWebAuthnCredentialsSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                "/iam.auth.v1.AuthService/DeleteWebAuthnCredential" => {
                    #[allow(non_camel_case_types)]
                    struct DeleteWebAuthnCredentialSvc<T: AuthService>(pub Arc<T>);
                    impl<
                        T: AuthService,
                    > tonic::server::UnaryService<super::DeleteWebAuthnCredentialRequest>
                    for DeleteWebAuthnCredentialSvc<T> {
                        type Response = super::DeleteWebAuthnCredentialResponse;
                        type Future = BoxFuture<
                            tonic::Response<Self::Response>,
                            tonic::Status,
                        >;
                        fn call(
                            &mut self,
                            request: tonic::Request<
                                super::DeleteWebAuthnCredentialRequest,
                            >,
                        ) -> Self::Future {
                            let inner = Arc::clone(&self.0);
                            let fut = async move {
                                <T as AuthService>::delete_web_authn_credential(
                                        &inner,
                                        request,
                                    )
                                    .await
                            };
                            Box::pin(fut)
                        }
                    }
                    let accept_compression_encodings = self.accept_compression_encodings;
                    let send_compression_encodings = self.send_compression_encodings;
                    let max_decoding_message_size = self.max_decoding_message_size;
                    let max_encoding_message_size = self.max_encoding_message_size;
                    let inner = self.inner.clone();
                    let fut = async move {
                        let method = DeleteWebAuthnCredentialSvc(inner);
                        let codec = tonic::codec::ProstCodec::default();
                        let mut grpc = tonic::server::Grpc::new(codec)
                            .apply_compression_config(
                                accept_compression_encodings,
                                send_compression_encodings,
                            )
                            .apply_max_message_size_config(
                                max_decoding_message_size,
                                max_encoding_message_size,
                            );
                        let res = grpc.unary(method, req).await;
                        Ok(res)
                    };
                    Box::pin(fut)
                }
                _ => {
                    Box::pin(async move {
                        let mut response = http::Response::new(
                            tonic::body::Body::default(),
                        );
                        let headers = response.headers_mut();
                        headers
                            .insert(
                                tonic::Status::GRPC_STATUS,
                                (tonic::Code::Unimplemented as i32).into(),
                            );
                        headers
                            .insert(
                                http::header::CONTENT_TYPE,
                                tonic::metadata::GRPC_CONTENT_TYPE,
                            );
                        Ok(response)
                    })
                }
            }
        }
    }
    impl<T> Clone for AuthServiceServer<T> {
        fn clone(&self) -> Self {
            let inner = self.inner.clone();
            Self {
                inner,
                accept_compression_encodings: self.accept_compression_encodings,
                send_compression_encodings: self.send_compression_encodings,
                max_decoding_message_size: self.max_decoding_message_size,
                max_encoding_message_size: self.max_encoding_message_size,
            }
        }
    }
    /// Generated gRPC service name
    pub const SERVICE_NAME: &str = "iam.auth.v1.AuthService";
    impl<T> tonic::server::NamedService for AuthServiceServer<T> {
        const NAME: &'static str = SERVICE_NAME;
    }
}
